[project]
name = "data-cience-code"
version = "0.1.0"
description = "Data Cience Code Ayudantia 2do Semestre 2026"
readme = "README.md"
authors = [
    { name = "MrMurlock", email = "49298120+MrMurlock@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fg-data-profiling>=4.20.0",
    "matplotlib>=3.11.2",
    "numpy>=2.3.5",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "scipy>=1.18.1",
    "seaborn>=0.13.2",
    "setuptools<82",
]

[project.scripts]
data-cience-code = "data_cience_code:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
